export const environment = {
    production: false,
    apiKey: 'eyJhbGciOiJIUzI1NiJ9.eyJhdWQiOiIyMmE3MjYxMzUwZDM5MWExZGRmNDQ1OGUyMTMyNzkwZCIsIm5iZiI6MTc0MTE5MTAwOC4yMDg5OTk5LCJzdWIiOiI2N2M4Nzc2MDkwMzU1YzY0NTc2ZTVkNjgiLCJzY29wZXMiOlsiYXBpX3JlYWQiXSwidmVyc2lvbiI6MX0.1RkkW1x4_MJK2OhThHhHVunR0shkGgoACutVCqEvxFA'
};